language: go

go:
- 1.8.x

deploy:
  provider: releases
  api_key:
    secure: vnqynWd88gs1FwdAd9a1++pFZDrDda2aN9/CfyeWWXm7SPI3glSb4B4Eo0sAcK6EHeiupGK8dkH+Onnro4538evT/bEud7Y2Zsommkf9HInTpVaf5EqO33CnD1Bz1yhTF0if28BYUuWueiDtvqQoUjx5Mi+jZVXhvv2XKU+xtApZdV1Ej3yMLGpx/to0dwqSGnRrdIWTqAYgEGhNWlCCaZxNME+Jg9uJoKDFTtmSuqCmMzCv354k5eQWTXjHh49x6vR5GVMBWLMwKWen57QAfUlbkFJYrw8FETSF8lT8T3v1BvVgukOqlbVjovVeByRouhFoPyzY1ZM4+klnOePwXs/6LFKekAuywPd3JhPylPXp+rHrm/Lu/7aCNvPUQoYthlvaTkRbEAqshNH7uAK5bPMbVt37oLboQPvz0ODA40N33oeSJ2FR+iPfsM7PMwvbLGLRrH9Ndmc64Iv7wnnPQAePyxOwDhk5KzWCIy/4tgfVdJg3RfGj4X+ym/yWCZMQAOpLd8Yq8jZ1VDiHvlSSlkIuuHyqBTSCCMiE7/bfYwirIbuTVyaNqydMOB07e3D0RHkgq+1YtIhXPylMWVcDB3BG+GaTrRNJg+mVBdYfvj7B5EC79d1DcZGWGymq0QhFtpNd8JRIh7kXDS6tUlys3gSB7HZsmgiCVU6tOLQcIKY=
  file: btrdedup
  on:
    tags: true
